title = "Minimal Gitleaks Config"

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["GitHub", "token"]

[[rules]]
id = "aws-secret"
description = "AWS Secret Access Key"
regex = '''(?i)aws_secret_access_key(.{0,20})?["'][0-9a-zA-Z\/+=]{40}["']'''
tags = ["AWS", "key"]
