title = "Gitleaks config"

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)["']?([A-Z0-9]{40})["']?'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''(?i)aws(.{0,20})?(?-i)["']?([A-Z0-9]{20})["']?'''
tags = ["key", "AWS"]
