name: Gitleaks Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks

      - name: Run Gitleaks
        run: |
          ./gitleaks detect --source . --no-git --redact --config .gitleaks.toml
